language: java

install: true
before_script: "./ci-resources/before-build.sh"
script: "./ci-resources/build.sh"

cache:
  directories:
  - "$HOME/.m2/repository"

branches:
  except:
    - /^release-.*$/
    - /^hotfix-.*$/